### ISSUE TITLE
Нет погодной сводки на ближайшие 2 дня

### ISSUE THREAD

**Issue by brualan** [msoap/yandex-weather-cli#12]
> Прогноз погоды в Москве на 10 дней — Яндекс.Погода (https://yandex.ru/pogoda/)
Сейчас: 4 °C - Пасмурно
Давление: 742 мм рт. ст.
Влажность: 89%
Ветер: 5,2 м/с, Ю
────────────────────────────────────────────────────────
 18  19  20  21  22  23   0   1   2   3   4   5   6   7
▁▁▁▁▁▁▁▁▁▁▂▂▃▃▄▄▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▆▆▇▇▇▇
  4°  4°  4°  5°  6°  6°  6°  6°  6°  6°  6°  6°  6°  7°
          ☂   ☂                       ☂           ☂
────────────────────────────────────────────────────────
 дата         °C погода                        °C ночью
────────────────────────────────────────────────────────
 06.11 (ср)   0° снег                                1°
 07.11 (чт)  -2° небольшой снег                     -3°
 08.11 (пт)   0° небольшой снег                     -2°
 09.11 (сб)   2° небольшой снег                      1°
 10.11 (вс)   4° снег                                6°
 11.11 (пн)   9° небольшой дождь                     9°
 12.11 (вт)  13° небольшой дождь                    10°
 13.11 (ср)  10° небольшой дождь                     9°
 14.11 (чт)   6° небольшой дождь                     3°
 15.11 (пт)   4° пасмурно                            1°
 16.11 (сб)   4° небольшой дождь                     5°
 17.11 (вс)   6° небольшой дождь                     6°
 18.11 (пн)   7° небольшой дождь                     1°
 19.11 (вт)   2° небольшой снег                      0°
 20.11 (ср)   3° пасмурно                            1°
 21.11 (чт)   2° пасмурно                            1°
 22.11 (пт)   1° дождь                               0°
 23.11 (сб)   2° пасмурно                            0°
 24.11 (вс)   1° дождь                               0°
 25.11 (пн)   1° пасмурно                           -1°
 26.11 (вт)   0° пасмурно                           -1°
 27.11 (ср)   0° пасмурно                            0°
 28.11 (чт)   1° пасмурно                           -1°
 29.11 (пт)   0° снег                               -2°
 30.11 (сб)   1° дождь                              -1°
 01.12 (вс)   0° снег                               -2°
 02.12 (пн)  -1° снег                               -2°
 03.12 (вт)  -1° пасмурно                           -3°
 04.12 (ср)  -1° снег                               -2°
 05.12 (чт)  -2° снег                               -4°
 06.12 (пт)  -4° снег                               -5°
 07.12 (сб)  -4° пасмурно                           -4°
 08.12 (вс)  -2° снег                               -3°
 09.12 (пн)  -2° снег                               -2°
 10.12 (вт)   0° снег                               -1°

Вывод программы прикрепил выше. Дата на момент запуска 03.11. Нет данных за 04.11 и 05.11 (завтра и послезавтра), но на сайте Яндекс.Погоды эти даты есть. Погоду на завтра и послезавтра хотелось бы знать тоже :)

P.S. Большое спасибо за утилиту, она сильно упростила жизнь

**Comment by msoap** [comment]
Это было исправлено в #11, точно используется последняя версия (1.14)?
Версию можно узнать, запустив `yandex-weather-cli -version`

**Comment by brualan** [comment]
Обновился с 1.13 до 1.14. Всё ок, спасибо
