### ISSUE TITLE
Cities written in cyrillic aren't working

### ISSUE THREAD

**Issue by tipok** [msoap/yandex-weather-cli#2]
If you try to get weather for London and do write it in cyrillic, the tool does not deliver any result e.g.:
~|⇒ yandex-weather-cli лондон
 (https://pogoda.yandex.ru/лондон)
Сейчас: 0 °C, , : 0 °C, : 0 °C
Давление:
Влажность:
Ветер:

**Comment by msoap** [comment]
Yes, because this page (https://pogoda.yandex.ru/лондон) is not responding.
Fixed for this case in 4e251886164abd60a45e0321be02d93c66ac9777.
