### ISSUE TITLE
No one city aren't working

### ISSUE THREAD

**Issue by AlexandrZorin** [msoap/yandex-weather-cli#6]
All queries about any city is answering "City not found".

**Comment by msoap** [comment]
Please provide example of city.
Does the page `https://yandex.ru/pogoda/city_name` (or `https://yandex.ru/pogoda/`) open in browser?

**Comment by AlexandrZorin** [comment]
For example, London before worked, maybe month ago. But now application is answering "City "London" not found". All cities including London is working in browser.

**Comment by msoap** [comment]
Please try the latest version - https://github.com/msoap/yandex-weather-cli/releases/tag/1.10
