### ISSUE TITLE
Text output damaged on Linux i386 (AMD Athlon XP 2800+) system

### ISSUE THREAD

**Issue by MojoByte** [msoap/yandex-weather-cli#8]
Terminal output is unexpectedly damaged. Please see attached image.

![yandex-weather](https://user-images.githubusercontent.com/49766774/56391707-5de44b80-6227-11e9-93be-170b5e31a14c.jpg)

---
uname -a
Linux bitcoinshell 3.16.63 #11 SMP Thu Mar 7 21:54:36 GMT 2019 i686 AMD Athlon(tm) XP 2800+ AuthenticAMD GNU/Linux

go version
go version go1.11.5 linux/386
---

yandex-weather-cli application has been compiled locally.

yandex-weather-cli executable from https://github.com/msoap/yandex-weather-cli/releases/download/1.13/yandex-weather-cli-1.13.linux.386.tar.gz archive fails with error "Illegal operation". For eliminating this error on machines with non-SSE2 CPU (AMD Athlon XP 2800+ is the case) the application should be cross compiled with GO386=387 option, i.e. like this:

env GOOS=linux GOARCH=386 GO386=387 make build

**Comment by MojoByte** [comment]
BTW, anyone can easily reproduce the issue cause it's observed at Linux server with free shell.

**Comment by msoap** [comment]
I think it depends on the installed fonts for your terminal emulator (Unicode support is required).

**Comment by apparluk** [comment]
yandex-weather-cli-1.13.linux.386.tar.gz

extracted and run on Slackware-14.2 inside 'uxterm' renders the expected output
